### ISSUE TITLE
Problem with deployment: . scripts/build-frontend-app.sh

### ISSUE THREAD

**Issue by toth12** [jakekara/lts-cloud#11]
. scripts/build-frontend-builder.sh works fine

but . scripts/build-frontend-app.sh (executed in lts-app folder) produces the following error:

Building frontend
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN lts-app No description
npm WARN lts-app No repository field.
npm WARN lts-app No license field.

up to date in 0.076s
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-01T17_05_23_850Z-debug.log

System: MAC OS Sierra 10.12.6

docker version

Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true

**Comment by jakekara** [comment]
It sounds like you may not have cloned the git submodule when you cloned this repository. Did you clone this repository using `git clone --recurse-submodules` ?

**Comment by toth12** [comment]
cheers, you are right;I have skipped that and used the normal git clone, but now that I am using that I have the following failure:

(I tested it on both Mac and Linux, and the same is the issue; isn't that "git@github.com:YaleDHLab/let-them-speak.git" should be something like "username@github.com:YaleDHLab/let-them-speak.git" ; let-them-speak is a closed repo so only contributors can theoretically access it? so I should be able to do so with my own username)

git clone --recurse-submodules https://github.com/jakekara/lts-cloud.git
Password:
Cloning into 'lts-cloud'...
remote: Enumerating objects: 2610, done.
remote: Counting objects: 100% (2610/2610), done.
remote: Compressing objects: 100% (960/960), done.
remote: Total 2610 (delta 1741), reused 2479 (delta 1614), pack-reused 0
Receiving objects: 100% (2610/2610), 2.23 MiB | 4.92 MiB/s, done.
Resolving deltas: 100% (1741/1741), done.
Submodule 'lts-app/let-them-speak' (git@github.com:YaleDHLab/let-them-speak.git) registered for path 'lts-app/let-them-speak'
Cloning into '/Users/gmt28/Documents/Workspace/lts-jake/lts-cloud/lts-app/let-them-speak'...
Warning: Permanently added the RSA host key for IP address '140.82.121.4' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:YaleDHLab/let-them-speak.git' into submodule path '/Users/gmt28/Documents/Workspace/lts-jake/lts-cloud/lts-app/let-them-speak' failed
Failed to clone 'lts-app/let-them-speak'. Retry scheduled
Cloning into '/Users/gmt28/Documents/Workspace/lts-jake/lts-cloud/lts-app/let-them-speak'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:YaleDHLab/let-them-speak.git' into submodule path '/Users/gmt28/Documents/Workspace/lts-jake/lts-cloud/lts-app/let-them-speak' failed
Failed to clone 'lts-app/let-them-speak' a second time, aborting

**Comment by jakekara** [comment]
Do you have github ssh authentication configured? 

If not, here are [the docs](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh) on how to set that up.

**Comment by jakekara** [comment]
I'm going to mark this closed.
