### ISSUE TITLE
Filtering Search Results in terms of metadata

### ISSUE THREAD

**Issue by toth12** [jakekara/lts-cloud#15]
@jakekara see this bug here:

https://www.dropbox.com/s/6krg80fote7mrhs/Bug.mov?dl=0

(I also shared it with you). I got this problem with both a new version of the data I produced now and with the old one, earlier uploaded to the amazon bucket. Can you reproduce it yourself? Or is it only happening on my machine?

**Comment by toth12** [comment]
error is related to that query to blacklab server is sent in a way that the metadata parameter misses an apostrophe, for instance:

http://localhost:8888/blacklab-server-1.7.3/lts/hits?first=0&limit=20&patt=%22kill%22&waitfortotal=true&outputformat=json&prettyprint=no&wordsaroundhit=5&filter=gender:%22female

**Comment by jakekara** [comment]
This is resolved in the main branch now.
